version: '3.9'
services:
  api:
    container_name: love-comme-server
    build: .
    ports:
      - 8000:8000
    tty: true
    volumes:
      - .:/go/src/love-comme-server
    env_file:
      - .env
